#!/usr/bin/zsh
# Operation in bash not guranteed.
# Copyright (c) 2024 Quantius Benignus
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#--------------------------------------------------------------------------

# NAME: wsiml (Multi-lingual version of wsi) 
# PREREQUSITES: 
#  - whisper.cpp 'main' AND/OR 'server' installation (see https://github.com/ggerganov/whisper.cpp) or a whisperfile
#  - recent versions of 'sox', 'curl', 'xsel' or 'wl-copy' CLI tools from your system's repositories.
#--------------------------------------------------------------------------
#Use those timestamps for timing your app/server performance:
#echo $(date +%s.%N)

#---USER CONFIGURATION BLOCK----------------------------------------------------------------
#The main configuration for this and all other BlahST tools is now in blahst.cfg, please, edit that file as needed.
source $HOME/.config/blahst.cfg
source $HOME/.local/bin/blahst-helpers
#Local overrides: 
# Choose a default language for speech input (only those with WER > 50%):
#lang="auto"
#    Afrikaans:
#lang="af"
#    Arabic:
#lang="ar"
#    Armenian:
#lang="hy"
#    Azerbaijani:
#lang="az"
#    Belarusian:
#lang="be"
#    Bosnian:
#lang="bs"
#    Bulgarian:
#lang="bg"
#    Catalan:
#lang="ca"
#    Chinese:
#lang="zh"
#    Croatian:
#lang="hr"
#    Czech:
#lang="cs"
#    Danish:
#lang="da"
#    Dutch:
#lang="nl"
#    English:
lang="en"
#    Estonian:
#lang="et"
#    Finnish:
#lang="fi"
#    French:
#lang="fr"
#    Galician:
#lang="gl"
#    German:
#lang="de"
#    Greek:
#lang="el"
#    Hebrew:
#lang="he"
#    Hindi:
#lang="hi"
#    Hungarian:
#lang="hu"
#    Icelandic:
#lang="is"
#    Indonesian:
#lang="id"
#    Italian:
#lang="it"
#    Japanese:
#lang="ja"
#    Kannada:
#lang="kn"
#    Kazakh:
#lang="kk"
#    Korean:
#lang="ko"
#    Latvian:
#lang="lv"
#    Lithuanian:
#lang="lt"
#    Macedonian:
#lang="mk"
#    Malay:
#lang="ms"
#    Maori:
#lang="mi"
#    Marathi:
#lang="mr"
#    Nepali:
#lang="ne"
#    Norwegian:
#lang="no"
#    Persian:
#lang="fa"
#    Polish:
#lang="pl"
#    Portuguese:
#lang="pt"
#    Romanian:
#lang="ro"
#    Russian:
#lang="ru"
#    Serbian:
#lang="sr"
#    Slovak:
#lang="sk"
#    Slovenian:
#lang="sl"
#    Spanish:
#lang="es"
#    Swahili:
#lang="sw"
#    Swedish:
#lang="sv"
#    Tagalog:
#lang="tl"
#    Tamil:
#lang="ta"
#    Thai:
#lang="th"
#    Turkish:
#lang="tr"
#    Ukrainian:
#lang="uk"
#    Urdu:
#lang="ur"
#    Vietnamese:
#lang="vi"
#    Welsh:
#lang="cy"
# Default whisper.cpp model file for inference (Use at least ggml-small for good non-english performance):
#model="$TEMPD/ggml-small.bin
model=${WHISPER_DMODEL:-"$HOME/CHANGE_PATH_TO/WHISPER_CPP/MODELS/HERE/ggml-small.bin"}
#---END USER CONFIG BLOCK------------------------------------------------------------------------

# Process command line arguments first
while [ $# -gt 0 ]; do
    case "$1" in
        -p|--primary)
            # To enable pasting with the middle mouse button
            PRIMESEL=1
            shift
            ;;
        -c|--clipboard)
            # This is transitional warning due to breaking change (will be removed in the future). Clipboard is now the default:
            desknote "Breaking Change:" "The '-c' flag is deprecated, since clipboard is now default. \n \
            Remove unnecessary '-c' from your desktop shortcut definitions. \n \
            To use primary selection as the text source, use the '-p' flag in your desktop shortcuts."
            shift
            ;;
        -w|--whisperfile)
            whf="$WHISPERFILE"
            shift
            ;;
        -t|--translate)
            TRANSLATING="true"
            shift
            ;;
        -l|--language)
            shift
            lang=$1
            shift
            ;;
        -n|--netapi)
            #This uses the hostname or IP and port specified in the config block
            #Can be overwritten when a command line argument IP:PORT is supplied
            IPnPORT="$WHOST:$WPORT" 
            if [[ "$(curl -s -f -o /dev/null -w '%{http_code}' $IPnPORT)" != "200" ]]; then
                echo "Can't connect to whisper.cpp server at provided address!" >&2   
                exit 1
            fi
            shift
            ;;
        -h|--help)
            echo "Usage: $0 [-p|--primary] [-n|--netapi] [-w|--whisperfile] [IP:PORT]"
            echo "  -p, --primary: Use PRIMARY selection instead of CLIPBOARD (default - the better choice when autopaste is on)"
            echo "  -l, --language: Choose an input language (different than the default)"
            echo "  -n, --netapi: Use whisper.cpp server with the host:port in the GONFIG block"
            echo "  -t, --translate: Translate to english (default is no translation)"
            echo "Any other command line flag is expected to come after and be a valid whisper.cpp flag/argument and will be passed to it as is."
            echo "For example: 'wsiml -l pl -t --best-of 7' is a valid call to wsiml"
            exit 0
            ;;
        *)
            #Anything else is passed along to whisper.cpp, so use the above flags first and know what you are doing:
            break
            ;;
    esac
done
# Store the remaining arguments in a variable
rem_args=("$@")

#Hear the complaints of the above tools and do not continue with the sequence:
set -e

#echo "Recording now: "$(date +%s.%N)

rec -q -t wav $ramf rate 16k silence 1 0.1 1% 1 2.0 5%  2>/dev/null

#echo "Sending now: "$(date +%s.%N)
if [ -n "$IPnPORT" ]; then 
# This is switching the models on the fly, but takes time, moving to sepparate apps for 'en' and 'multilingual'. 
#    if [ "$lang" != "en" ]; then
#        str=$(curl -S -s $IPnPORT/load \
#        -H "Content-Type: multipart/form-data" \
#        -F model="$TEMPD/ggml-small.bin")
#        echo $str
#        multi=1
#    else
#        if [ multi = 1 ]; then
#            str=$(curl -S -s $IPnPORT/load \
#            -H "Content-Type: multipart/form-data" \
#            -F model="$TEMPD/ggml-base.en.bin")
#            echo $str
#            multi=0
#        fi           
#    fi
#In principle, this request can be built up to handle most of the whisper parameters, but for now, only language and translation:
    str=$(curl -S -s $IPnPORT/inference \
        -H "Content-Type: multipart/form-data" \
        -F file="@$ramf" \
        -F language="$lang" \
        -F translate="${TRANSLATING:-false}" \
        -F temperature="0.0" \
        -F temperature_inc="0.2" \
        -F response_format="text")
# | jq -r '.text' )
elif [[ "$whf" == *.llamafile ]]; then
    echo "Using whisperfile: "
    str="$($whf -t $NTHR -nt -f $ramf -l $lang ${TRANSLATING:+-tr} ${rem_args[@]} 2>/dev/null)"     
else
    str="$(transcribe -t $NTHR -nt -m $model -f $ramf -l $lang ${TRANSLATING:+-tr} ${rem_args[@]} 2>/dev/null)" 
fi
#echo "$TRANSLATING from $lang"
#echo "Got text now: "$(date +%s.%N)

# Whisper detected non-speech events such as (wind blowing): 
str="${str/\(*\)}"   
str="${str/\[*\]}"
str="${str#$'\n'}"    
str="${str#$'\n'}"
#Prefer the power of zsh, but loose full POSIX compliance.
if [ -n "$ZSH_NAME" ]; then
    str="${str#*([[:space:]])}"
    str="${(u)str}"
elif [ -n "$BASH" ]; then
    #Running in bash because you changed the shebang on line 1
    str="${str##+([[:space:]])}"
    str="${str^}"
else
    echo "Unknown shell, assuming bash compliance"
    str="${str##+([[:space:]])}"
    str="${str^}"
fi

#We have a result, now we make a few decisions:
#If this is somehow run in a text console: 
if [[ -z "${DISPLAY}" ]] || [[ -z "${DESKTOP_SESSION}" ]] || [[ -z "${XDG_CURRENT_DESKTOP}" ]]; then
    #"Not running in a known graphics environment. Using standard output:
    echo $str ; exit 0
else
    #xsel or wl-copy:
    case "$wm" in
	"x11")
	    echo $str | { (( $PRIMESEL )) && xsel -ip || xsel -ib; }
	    autopaste $wm
	    ;;
	"wayland")
	    echo $str | { (( $PRIMESEL )) && wl-copy -p || wl-copy; }
	    autopaste $wm
	    ;;
	*)
	    echo $str
	    ;;
    esac
fi

#echo "Text processed and in clipboard now: "$(date +%s.%N)
